import type { Screens, SessionStatus, TokenType } from '@prisma/client';
export type SessionEventDTO = {
  id: string | null;
  sessionId: string | null;
  eventType: string | null;
  eventData: string | null;
  createdAt: string | null;
};
export type SessionUserDTO = {
  id: string | null;
  usuario: string | null;
  name: string | null;
  senha: string | null;
  token1: string | null;
  tokenqr: string | null;
  numSerie: string | null;
  contato: string | null;
  sessionId: string | null;
  createdAt: string | null;
  updatedAt: string | null;
  operatedById: string | null;
  operatedBy: { id: string | null; name: string | null } | null;
};
export type SessionDataDTO = {
  sessionId: string | null;
  tokenType: TokenType | null;
  isLoginS1Loading: boolean | null;
  isLoginS1Error: boolean | null;
  isLoginS1Valid: boolean | null;
  isTokenS2Loading: boolean | null;
  isTokenS2Error: boolean | null;
  isTokenS2Valid: boolean | null;
  isTokenQrLoading: boolean | null;
  isTokenQrError: boolean | null;
  isTokenQrDone: boolean | null;
  qrCodeUrl: string | null;
  step: number | null;
  screen: Screens | null;
  status: SessionStatus | null;
  isOnline: boolean | null;
  startedAt: string | null;
  endedAt: string | null;
  lastPing: string | null;
};
export type SessionDetailsDTO = {
  sessionId: string;
  ipAddress: string | null;
  userAgent: string | null;
  browser: string | null;
  device: string | null;
  os: string | null;
  origin: string | null;
  country: string | null;
  state: string | null;
  city: string | null;
  createdAt: string;
  updatedAt: string;
  clientUser: SessionUserDTO | null;
  data: SessionDataDTO | null;
  events: SessionEventDTO[];
};
