services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: sh -lc "npm run prisma:deploy && npm run db:seed || true; npm run start"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 12

  db:
    image: postgres:16-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: producao
      POSTGRES_DB: brada
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d brada"]
      interval: 5s
      timeout: 3s
      retries: 30

  proxy:
    image: nginx:1.27-alpine
    container_name: proxy
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata:
